name: Build Image

on: [ workflow_dispatch ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - name: CO Repo
        uses: actions/checkout@v3

      - name: Set Up Env
        run: |
          sed -i "s/$GLOBALS\['DBHOST'\] = '127.0.0.1';/$GLOBALS\['DBHOST'\] = 'db';/g" website/code/db_connection.php
          sed -i "s/$GLOBALS\['DBPASS'\] = '';/$GLOBALS\['DBPASS'\] = 'pass';/g" website/code/db_connection.php

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Image
        run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t jordanwmckee/polymer-selector:latest -f docs/Dockerfile --push .

